# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.core.grpc.protos import product_service_pb2 as src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/core/grpc/protos/product_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_product = channel.unary_unary(
            '/src.core.grpc.stubs.ProductService/create_product',
            request_serializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.CreateProductRequest.SerializeToString,
            response_deserializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.CreateProductResponse.FromString,
            _registered_method=True)
        self.get_product = channel.unary_unary(
            '/src.core.grpc.stubs.ProductService/get_product',
            request_serializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.GetProductByIdRequest.SerializeToString,
            response_deserializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.ProductByIdResponse.FromString,
            _registered_method=True)
        self.get_products = channel.unary_unary(
            '/src.core.grpc.stubs.ProductService/get_products',
            request_serializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.GetProductListRequest.SerializeToString,
            response_deserializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.ProductListResponse.FromString,
            _registered_method=True)
        self.update_product = channel.unary_unary(
            '/src.core.grpc.stubs.ProductService/update_product',
            request_serializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.UpdateProductRequest.SerializeToString,
            response_deserializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.UpdateProductResponse.FromString,
            _registered_method=True)
        self.delete_product = channel.unary_unary(
            '/src.core.grpc.stubs.ProductService/delete_product',
            request_serializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.DeleteProductRequest.SerializeToString,
            response_deserializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.DeleteProductResponse.FromString,
            _registered_method=True)


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_product(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_product(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_products(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_product(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_product(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'create_product': grpc.unary_unary_rpc_method_handler(
            servicer.create_product,
            request_deserializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.CreateProductRequest.FromString,
            response_serializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.CreateProductResponse.SerializeToString,
        ),
        'get_product': grpc.unary_unary_rpc_method_handler(
            servicer.get_product,
            request_deserializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.GetProductByIdRequest.FromString,
            response_serializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.ProductByIdResponse.SerializeToString,
        ),
        'get_products': grpc.unary_unary_rpc_method_handler(
            servicer.get_products,
            request_deserializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.GetProductListRequest.FromString,
            response_serializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.ProductListResponse.SerializeToString,
        ),
        'update_product': grpc.unary_unary_rpc_method_handler(
            servicer.update_product,
            request_deserializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.UpdateProductRequest.FromString,
            response_serializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.UpdateProductResponse.SerializeToString,
        ),
        'delete_product': grpc.unary_unary_rpc_method_handler(
            servicer.delete_product,
            request_deserializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.DeleteProductRequest.FromString,
            response_serializer=src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.DeleteProductResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'src.core.grpc.stubs.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('src.core.grpc.stubs.ProductService', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_product(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.core.grpc.stubs.ProductService/create_product',
            src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.CreateProductRequest.SerializeToString,
            src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.CreateProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_product(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.core.grpc.stubs.ProductService/get_product',
            src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.GetProductByIdRequest.SerializeToString,
            src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.ProductByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_products(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.core.grpc.stubs.ProductService/get_products',
            src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.GetProductListRequest.SerializeToString,
            src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.ProductListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_product(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.core.grpc.stubs.ProductService/update_product',
            src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.UpdateProductRequest.SerializeToString,
            src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.UpdateProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_product(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.core.grpc.stubs.ProductService/delete_product',
            src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.DeleteProductRequest.SerializeToString,
            src_dot_core_dot_grpc_dot_protos_dot_product__service__pb2.DeleteProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
