"""Add table relationships for product

Revision ID: 2a09bf88961a
Revises: 64f432430d9d
Create Date: 2025-07-19 12:34:38.936878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a09bf88961a'
down_revision: Union[str, None] = '64f432430d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=35), nullable=False),
    sa.Column('main', sa.BOOLEAN(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=True)
    op.create_table('product_categories',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    op.create_table('product_colors',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('color_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'color_id')
    )
    op.create_unique_constraint(None, 'colors', ['title'])
    op.add_column('products', sa.Column('type_id', sa.UUID(), nullable=False))
    op.add_column('products', sa.Column('collection_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'products', 'types', ['type_id'], ['id'])
    op.create_foreign_key(None, 'products', 'collections', ['collection_id'], ['id'])
    op.drop_column('products', 'color')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'type')
    op.drop_column('products', 'material')
    op.create_unique_constraint(None, 'types', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'types', type_='unique')
    op.add_column('products', sa.Column('material', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('type', sa.VARCHAR(length=35), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('color', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'collection_id')
    op.drop_column('products', 'type_id')
    op.drop_constraint(None, 'colors', type_='unique')
    op.drop_table('product_colors')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
