"""Fix Product.image_title_prefix length

Revision ID: 2b500bac0544
Revises: 5ce84252a51b
Create Date: 2025-07-27 11:43:31.405998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b500bac0544'
down_revision: Union[str, None] = '5ce84252a51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'title',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('products', 'image_title_prefix',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image_title_prefix',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('images', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=35),
               existing_nullable=False)
    # ### end Alembic commands ###
