"""Add image prefix for product

Revision ID: 5ce84252a51b
Revises: 2a09bf88961a
Create Date: 2025-07-19 12:41:01.186248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce84252a51b'
down_revision: Union[str, None] = '2a09bf88961a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_title_prefix', sa.VARCHAR(length=30), nullable=False))
    op.create_unique_constraint(None, 'products', ['image_title_prefix'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'image_title_prefix')
    # ### end Alembic commands ###
