"""Fix: Image.product_image_title_prefix

Revision ID: 5dcc3035dedb
Revises: 9fce76ba31fc
Create Date: 2025-07-27 21:05:38.031388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dcc3035dedb'
down_revision: Union[str, None] = '9fce76ba31fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('product_image_title_prefix', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(op.f('images_product_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'products', ['product_image_title_prefix'], ['image_title_prefix'])
    op.drop_column('images', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_product_id_fkey'), 'images', 'products', ['product_id'], ['id'])
    op.drop_column('images', 'product_image_title_prefix')
    # ### end Alembic commands ###
