"""Add DateTime field to Product

Revision ID: 7a92f477a4df
Revises: 5dcc3035dedb
Create Date: 2025-08-04 18:48:48.915808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a92f477a4df'
down_revision: Union[str, None] = '5dcc3035dedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('images_title_key'), 'images', type_='unique')
    op.create_unique_constraint('uniq_image__product_prefix', 'images', ['product_image_title_prefix', 'title'])
    op.add_column('products', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'created_at')
    op.drop_constraint('uniq_image__product_prefix', 'images', type_='unique')
    op.create_unique_constraint(op.f('images_title_key'), 'images', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
